apiVersion: apps/v1
kind: Deployment
metadata:
  name: logmessageprocessor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logmessageprocessor
  template:
    metadata:
      labels:
        app: logmessageprocessor
    spec:
      containers:
        - name: logmessageprocessor
          image: automationrepository.azurecr.io/logmessageprocessor-image
          ports:
            - containerPort: 6029
          env:
            - name: REDIS_HOST
              value: "redis"
            - name: REDIS_PORT
              value: "6379"
            - name: REDIS_CHANNEL
              value: "log_channel"
            - name: ZIPKIN_URL
              value: "http://zipkin:9411/api/v2/spans"
